version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "notification-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-e36o4zng1pcj"
s3_prefix = "notification-aws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
