AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  msc-assignment-1

  Sample SAM Template for msc-assignment-1
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WriteNotificationData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: WriteNotificationData
      CodeUri: msc-assignment/
      Handler: WriteNotification.handler
      Runtime: nodejs12.x
      Policies:
        - AmazonDynamoDBFullAccess 
        #- DynamoDBCrudPolicy:
        #    TableName: !Ref NotificationTable 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /notification
            Method: post
            # RestApiId: !Ref WriteNotificaitonApi
            # RequestModel: 
            #  Model: RequestClass # REQUIRED; must match the name of a model defined in the Models property of the AWS::Serverless::API
            #  Required: true # OPTIONAL; boolean

  SendEmailFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: SendEmailFunc
      CodeUri: msc-assignment/
      Handler: SendEmail.handler
      Runtime: nodejs12.x
      Policies:
        - SESCrudPolicy:
            IdentityName: jayasai.kliq@gmail.com
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt NotificationTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON  

  NotificationTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Notification
      AttributeDefinitions: 
        - AttributeName: NotificationID
          AttributeType: S
      KeySchema: 
        - AttributeName: NotificationID
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE        


  # For API Gateway       
  # WriteNotificaitonApi:
  #     Type: AWS::Serverless::Api
  #     Properties:
  #       StageName : prod
  #       Models:
  #        RequestClass : 
  #         type: object
  #         properties:
  #           NotificationID:
  #            type: string
  #           NotificationBody:
  #            type: string
  #           NotificationEmail:
  #            type: string

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WriteNotificaitonApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WriteNotificationData:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt WriteNotificationData.Arn
  WriteNotificationDataIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WriteNotificationDataRole.Arn
